
spring:
  security:
    user:
      name: user
      password: 1234

server:
  port: 8080
---
spring:
  datasource:
    url: jdbc:mysql://localhost/easybank?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234
